apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: object-detection
  template:
    metadata:
      labels:
        app: object-detection
    spec:
      containers:
      - name: object-detection
        image: abal0041/assignment_1:2.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: 512Mi
            cpu: "0.5"
          limits:
            memory: 512Mi
            cpu: "0.5"